# -*- coding: utf-8 -*-
"""Desafio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xu8Un6g4SOEgVISafaITVOplM-MAqZ4k
"""

#Adicionar Livros
def AddLivro(LivroDic,Livrocounter):
  Titulo = input("Escreva o titulo: ")
  Autor = input("Escreva o autor: ")
  Genero = input("Escreva o genero: ")
  LivroDic[Livrocounter] = [Titulo,Autor,Genero]
  Livrocounter += 1
  return LivroDic,Livrocounter

#Remover Livros
def RemoveLivro(LivroDic):
  Titulo_To_Remove = input("Escreva o titulo do livro que deseja remover: ")
  LivrosCorrespondentes = {key:Livroinfo for key, Livroinfo in LivroDic.items()
  if Livroinfo[1].lower() == Titulo_To_Remove.lower()}

  if not LivrosCorrespondentes:
    print(f"Nenhum livro encontrado com o titulo especificado: '{Titulo_To_Remove}'.")
    return

  print(f"Livros encontrados com o titulo '{Titulo_To_Remove}':")
  for key, Livroinfo in LivrosCorrespondentes.items():
    print(f"ID: {key}, Titulo: {Livroinfo[0]}, Autor: {Livroinfo[1]}, Genero: {Livroinfo[2]}")

  try:
    ID_To_Remove = int(input("Digite o ID do livro que deseja remover: "))
    if ID_To_Remove in LivrosCorrespondentes:
      del LivroDic[ID_To_Remove]
      print(f"ID {ID_To_Remove} e titulo '{Titulo_To_Remove}' removido com sucesso.")
    else:
      print("Livro não encontrado com esse ID")
  except ValueError:
    print("ID inválido")

#Listar todos os livros de uma categoria
def ListarLivrosPorGenero(LivroDic):
  Genero_To_List = input("Escreva o genero do livro que deseja listar: ")
  LivrosCorrespondentes = {key:Livroinfo for key, Livroinfo in LivroDic.items()
  if Livroinfo[2].lower() == Genero_To_List.lower()}
  if not LivrosCorrespondentes:
    print(f"Nenhum livro encontrado com o genero especificado: '{Genero_To_List}'.")
    return
  print(f"Livros encontrados com o genero '{Genero_To_List}':")
  for key, Livroinfo in LivrosCorrespondentes.items():
    print(f"ID: {key}, Titulo: {Livroinfo[0]}, Autor: {Livroinfo[1]}, Genero: {Livroinfo[2]}")


#Listar Livros
def ListarLivros(LivroDic):
  if not LivroDic:
    print("Nenhum livro cadastrado")
    return
  print("Livros Cadastrados:")
  for key, Livroinfo in LivroDic.items():
    print(f"ID: {key}, Titulo: {Livroinfo[0]}, Autor: {Livroinfo[1]}, Genero: {Livroinfo[2]}")

Livros={}
Livrocounter=1
while True:
  print("Menu")
  print("1. Adicionar livro")
  print("2. Remover livro")
  print("3. Listar livros por genero")
  print("4. Listar livros")
  print("5. Sair")
  Escolha = int(input("Escolha uma opção: "))

  try:
    match Escolha:
      case 1:
        Livros, Livrocounter = AddLivro(Livros,Livrocounter)
      case 2:
        RemoveLivro(Livros)
      case 3:
        ListarLivrosPorGenero(Livros)
      case 4:
        ListarLivros(Livros)
      case 5:
        print("Saindo...")
        break
      case _:
        print("Opção inválida")
  except ValueError:
    print("Opção inválida")